### ISSUE TITLE
Using --no_footprint causes error code 404 

### ISSUE THREAD

**Issue by Xyntexx** [TousstNicolas/JLC2KiCad_lib#20]
Using the `--no_footprint` argument causes error 404.

### To Reproduce
Run the code with the following arguments:
`JLC2KiCad_lib.py C1337258 C24112 -dir My_lib -schematic_lib My_Schematic_lib --no_footprint`

Causes the following error:
`2022-10-25 22:01:05,540 - INFO - creating library for component C1337258
Traceback (most recent call last):
  File "JLC2KiCadLib\JLC2KiCad_lib\JLC2KiCadLib\JLC2KiCadLib.py", line 134, in main
    add_component(component, args)
  File "JLC2KiCadLib\JLC2KiCad_lib\JLC2KiCadLib\JLC2KiCadLib.py", line 38, in add_component
    _, datasheet_link, _ = get_footprint_info(component_id)
ValueError: not enough values to unpack (expected 3, got 0)
2022-10-25 22:01:09,648 - ERROR - create_footprint error. Requests returned with error code 404`

**Comment by TousstNicolas** [comment]
Fixed in PR #21 thank you for it.
